### ISSUE TITLE
Missing Nintendo - Sufami Turbo

### ISSUE THREAD

**Issue by lasers** [libretro/retroarch-assets#65] opened 2016-11-20 13:22 UTC
```
find -iname *suf*
./monochrome/png/Nintendo - Sufami Turbo.png
./pixel/png/Nintendo - Sufami Turbo.png
./retroactive/png/Nintendo - Sufami Turbo.png
./neoactive/png/Nintendo - Sufami Turbo.png
./retroactive_marked/png/Nintendo - Sufami Turbo.png
./retroactive_marked/src/Nintendo - Sufami Turbo.svg
```

No content.

**Comment by lasers** [comment] 2016-11-20 15:21
**Missing Nintendo - Game and Watch**
```
./monochrome-jagged/png/Nintendo - Game and Watch.png
./monochrome-jagged/png/? ? ? ? ? ? ? ? ? ? ? ? ? ? ?
./monochrome-jagged/png/Game and Watch.png
./monochrome-jagged/png/Game and Watch-content.png
./monochrome/png/Nintendo - Game and Watch.png
./monochrome/png/? ? ? ? ? ? ? ? ? ? ? ? ? ? ?
./monochrome/png/Game and Watch.png
./monochrome/png/Game and Watch-content.png
./monochrome/src/Nintendo - Game and Watch.svg
./monochrome/src/? ? ? ? ? ? ? ? ? ? ? ? ? ? ?
./monochrome/src/Game and Watch-content.svg
./pixel/png/Nintendo - Game and Watch.png
./pixel/png/? ? ? ? ? ? ? ? ? ? ? ? ? ? ?
./retroactive/png/Nintendo - Game and Watch-content.png
./retroactive/png/Nintendo - Game and Watch.png
./retroactive/png/Game and Watch.png
./retroactive/png/Game and Watch-content.png
./neoactive/png/Nintendo - Game and Watch-content.png
./neoactive/png/Nintendo - Game and Watch.png
./neoactive/png/Game and Watch.png
./neoactive/png/Game and Watch-content.png
./retroactive_marked/png/Nintendo - Game and Watch.png
./retroactive_marked/src/Nintendo - Game and Watch.svg
```
No content. We stopped using `Nintendo - Game and Watch`?

**Comment by baxysquare** [comment] 2016-11-22 19:12
I'm not sure how or if I can help you with this as a theme contributor.  I've tried to make sure that the RetroActive and NeoActive themes every icon that is included in the baseline Monochrome theme.  That's why there's a duplicate set of icons named "Nintendo - Game and Watch" and "Game and Watch".

**Comment by lasers** [comment] 2016-11-22 19:34
I think `Nintendo - Game and Watch` might be depreciated in favor of `Game & Watch` (apparently made by Nintendo) so we may have duplicate contents for same thing.

You don't have to do anything if you don't want to as I'm only sharing my findings... and I only see 12 games for Nintendo - Sufami Turbo (All Japan) in the database so most people might not notice this obscure game system... just like Pokemon Mini.

**Comment by lasers** [comment] 2016-11-22 19:40
@lollo78 Up for it? baxysquare would use your Sufami icon to complete other themes.

**Comment by baxysquare** [comment] 2016-11-22 19:42
It's sort of odd that most of the time the syntax is "Manufacturer - System" but there are exceptions such as "Game and Watch" as well as "Neo Geo," which I apparently ended up making a duplicate of as "SNK - Neo Geo."  Is there any way we can officially standardize it for consistency or am I making a mountain out of a mole hill?

**Comment by lasers** [comment] 2016-11-22 19:56
I cleaned up cheat dirs to stay consistent. Thumbnails have been standardized. I filed bug issues reporting that the `Content Downloader` isn't consistent right now. I don't think you're making a mountain of a mole hill.

I believe this is the database that RetroArch (and many other groups) have been using to standardize things. You can see it in `${CORE}.info`. 
```
"Atari - 2600"
"Atari - 5200"
"Atari - 7800"
"Atari - Jaguar"
"Atari - Lynx"
"Bandai - WonderSwan Color"
"Bandai - WonderSwan"
"Cave Story"
"DOOM"
"FB Alpha - Arcade Games"
"GCE - Vectrex"
"Game and Watch"
"Lutro"
"MAME"
"MAME2003"
"Magnavox - Odyssey2"
"Microsoft - MSX"
"Microsoft - MSX2"
"NEC - PC Engine - TurboGrafx 16"
"NEC - PC Engine CD - TurboGrafx-CD"
"NEC - PC Engine SuperGrafx"
"NEC - PC-FX"
"Nintendo - Famicom Disk System"
"Nintendo - Game Boy Advance (e-Cards)"
"Nintendo - Game Boy Advance"
"Nintendo - Game Boy Color"
"Nintendo - Game Boy"
"Nintendo - GameCube"
"Nintendo - Nintendo 64"
"Nintendo - Nintendo 64DD"
"Nintendo - Nintendo DS (Download Play) (BETA)"
"Nintendo - Nintendo DS Decrypted"
"Nintendo - Nintendo Entertainment System"
"Nintendo - Pokemon Mini"
"Nintendo - Sufami Turbo"
"Nintendo - Super Nintendo Entertainment System"
"Nintendo - Virtual Boy"
"Nintendo - Wii"
"Quake1"
"RPG Maker 2000"
"RPG Maker 2003"
"SNK - Neo Geo Pocket Color"
"SNK - Neo Geo Pocket"
"ScummVM"
"Sega - 32X"
"Sega - Dreamcast"
"Sega - Game Gear"
"Sega - Master System - Mark III"
"Sega - Mega Drive - Genesis"
"Sega - Mega-CD - Sega CD"
"Sega - NAOMI"
"Sega - PICO"
"Sega - SG-1000"
"Sega - Saturn"
"Sinclair - ZX 81"
"Sinclair - ZX Spectrum +3"
"Sinclair - ZX Spectrum"
"Sony - PlayStation Portable"
"Sony - PlayStation"
"The 3DO Company - 3DO"
"Uzebox"
```

**Closed** 2016-12-07 19:04 UTC
