### ISSUE TITLE
New icons request

### ISSUE THREAD

**Issue by Arnochocobo** [libretro/retroarch-assets#90] opened 2017-01-11 23:59 UTC
Hello Baxy! 
First of all, thanks a lot for your great job.
As you know there are multiple versions and dedicated versions of FBA (for neogeo, and capcom games).
You already did good looking icons for Neogeo, but it would be great to also have dedicated icons for Capcom CP1, 2 and 3. (many people prefer to separate those, instead of having a giant arcade folder)
Here are a few examples of what would be good candidate for those icons:

Capcom CP1  -> https://www.loveroms.com/assets/img/consoles/logos/capcom-play-system-1.png
Capcom CP1-content  -> https://upload.wikimedia.org/wikipedia/en/8/85/Cps1_board.gif
Capcom CP2  -> http://3.bp.blogspot.com/-HKOWnTgBMbc/VABfZdHo1EI/AAAAAAAAAsM/HKL-CxBFdtY/s1600/Nova%2BImagem%2Bde%2BBitmap%2B(3)09.png
Capcom CP2-content  -> http://i.ebayimg.com/images/g/3VMAAOSwDk5TveeQ/s-l300.jpg  (pic was taken from an angle, but have a proper top view, and keeping the green color (for Japan) would be great)
Capcom CP3  -> https://i.ytimg.com/vi/bSS2FWp0ZZo/hqdefault.jpg   (lower half)
Capcom CP3-content  -> http://thumbs.worthpoint.com/zoom/images1/1/0313/27/capcom-cpsiii-cps3-cp3-security_1_5e00756e707613356eaf399ff7fbd7bb.jpg

It would also be great if you could keep the original location of the stickers on those.
Thanks!

**Comment by baxysquare** [comment] 2017-01-12 21:04
I'd be happy to try and work up some CP icons.  The cabinet and board icons I used for MAME are based on a SF2 CP1 board and a 3KOAM Z-Back cabinet. If you have preferred cabinet or board designs, let me know.  I can't really use the logos for the designs in order to maintain continuity.

FYI, the NAOMI board and cabinet are also on my to-do list as well.  If there's any other requests, feel free to send them my way.

**Comment by Arnochocobo** [comment] 2017-01-13 12:59
Great, sounds amazing! Naomi emulation is not for tomorrow in retroarch, but probably one day. Looking forward to see what you will make and have Lakka look even better and more organized once your icons will be implemented! Thanks once again. Speaking of cabinets, it might be cool to have more japanese type cabinets for the sake of diversity. Here are a few popular ones, here in Japan  http://hard--candy.com/uploads/EgretII/Profile.jpg    https://s-media-cache-ak0.pinimg.com/564x/13/77/82/1377829fe8338af0975092628172004f.jpg    http://i.ebayimg.com/images/g/JM4AAOSwT6pVqLkC/s-l300.jpg http://wiki.arcadeotaku.com/images/a/a7/Sega_Blast_City_JP.jpg and the more recent http://www.manjiro.com/images/Net%20City%20cabinet.jpg

**Comment by Arnochocobo** [comment] 2017-01-13 13:05
Found something better for CP3-content 
https://ec.tops-game.jp/upload/save_image/05072249_51890668520a0.jpg   Don't forget the security card :)

**Comment by Arnochocobo** [comment] 2017-01-14 00:17
One more thing for CP2, can you prepare the different colors used in the different region?

Region	Case	
Japan	Green plastic
Euro/Etc./World	Blue plastic	
Asia	Grey plastic	
Brazil	Orange plastic
Rental	Yellow plastic

With those 5 colors, we will have the full CP2 spectrum. Thanks!  (Next step after that is to bug Kivutar so we can have specific icon per game in the playlist as a setting :) )

**Comment by baxysquare** [comment] 2017-01-17 21:17
I did some additional research and found some Capcom cabs that seemed to be a more natural fit.  The Impress represents the CP System I along with a CP Dash case for content.  As requested, I created the CP System II cases in color variations.  I ended up using a Big Blue Q Sound to represent the CP System II, but there is an Egret II variation labeled as a Japanese version if you feel inclined to change. The Q Grand Am 25 seemed to fit well with the CP System III with a CD and security cartridge to represent content.

For now, you can check out the work at [baxy-retroarch-themes](https://github.com/baxysquare/baxy-retroarch-themes) and navigate to the Capcom section of the theme and format you choose.  I'm still waiting on the NeoActive pull request to be merged but as soon as it is, I'll upload a massive update for Systematic and RetroActive.

**Comment by baxysquare** [comment] 2017-01-18 16:51
The CP System icons have been added to the NeoActive, RetroActive and Systematic themes.  Let me know if you need anything else!

**Comment by Arnochocobo** [comment] 2017-01-18 23:59
I love what you did with CP1 and 2, they look great! For the CP3 however, would you have a way to draw a small replica of the PCB with the cart, or have the card under it? Current icon shows a CD and the cart, but many games didn't even have the CD (they are labeled as NO CD in Mame and FBA). I also would like to show you what I did with your icons, please let me know where I can send you a .jpg

**Comment by twinaphex** [comment] 2017-01-19 10:26
We still need icons for GamePark 32 (GP32) and Tiger Game.com (for Monochrome at least).

**Comment by baxysquare** [comment] 2017-01-23 17:01
@Arnochocobo Thanks for clarifying that detail on CP3.  Going off image searches and articles led me to believe that CP3 was a CD system with Security Card.  I will work on a CP3 mobo design for you and re-label the CD version as an alternate design.

**Comment by baxysquare** [comment] 2017-01-23 17:07
@twinaphex @Kivutar I've really tried to steer clear of contributing to Monochrome but if you're okay with icons that have been adapted from my designs, complete with the 232x232 size might be considered a flaw, I'm happy to do what's needed.

![game park - gp32-content](https://cloud.githubusercontent.com/assets/17163726/22213957/4e4baa76-e153-11e6-8347-3c24a4b69efe.png)
![game park - gp32](https://cloud.githubusercontent.com/assets/17163726/22213959/4e4d8ad0-e153-11e6-8af4-b88ec1ad1853.png)
![tiger - game com-content](https://cloud.githubusercontent.com/assets/17163726/22213958/4e4d1cd0-e153-11e6-93fb-4878a9e45bd9.png)
![tiger - game com](https://cloud.githubusercontent.com/assets/17163726/22213956/4e4a97ee-e153-11e6-811b-59101b7ae5aa.png)

**Comment by baxysquare** [comment] 2017-01-23 20:57
Before I upload I wanted to get an opinion from @Arnochocobo.  Here's the original CD/card, an empty mobo, a mobo/card (which will likely be default) and a mobo/CD/card version.
![capcom---cp-system-iii-cd-content](https://cloud.githubusercontent.com/assets/17163726/22222284/80c9344e-e173-11e6-9caf-a4e2679b681f.png)
![capcom---cp-system-iii-content_mobo](https://cloud.githubusercontent.com/assets/17163726/22222287/846dfbb6-e173-11e6-8233-928def073346.png)
![capcom---cp-system-iii-content](https://cloud.githubusercontent.com/assets/17163726/22222301/8c6b203c-e173-11e6-98d4-6da7e2aefdcd.png)
[Capcom - CP System III-content_combo.pdf](https://github.com/libretro/retroarch-assets/files/724928/Capcom.-.CP.System.III-content_combo.pdf)

**Comment by Arnochocobo** [comment] 2017-01-25 14:35
I would go with number 3, thanks a lot for your quick feedback :)

**Comment by baxysquare** [comment] 2017-01-26 19:45
So I uploaded the complete set to Systematic, and set number 3 as the default.  I also replaced the default icon in RetroActive and NeoActive.  If this takes care of this issue, please feel free to close it at your convenience.

**Comment by baxysquare** [comment] 2017-03-23 16:30
@Arnochocobo I'd love to see what you did with the icons as you mentioned on Jan. 18.  Let me know if you have any other icon requests.  Otherwise, feel free to close this thread.  Thanks!

**Comment by baxysquare** [comment] 2017-07-26 22:55
@Arnochocobo I went ahead and closed this thread.  If you feel the issue is not resolved, please let us know.

**Closed by baxysquare** 2017-07-26 22:55 UTC
